media:
  input: assets/img
  output: media

content:
  - name: posts-en
    label: Posts (EN)
    path: content/en/posts
    type: collection
    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc
        
  - name: posts-th
    label: Posts (TH)
    path: content/th/posts
    type: collection
    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc


