media:
  input: assets/img
  output: media

content:
  - name: posts-en
    label: Posts
    path: content/en
    type: collection
  - name: posts-th
    label: Posts
    path: content/th
    type: collection
