media:
  input: assets/img
  output: media

content:
  - name: posts-en
    label: Posts (EN)
    path: content/en/posts
    type: collection
  - name: posts-th
    label: Posts (TH)
    path: content/th/posts
    type: collection
