media:
  input: assets/img
  output: media

content:
  - name: posts-en
    label: Posts (EN)
    path: content/en/posts
    type: collection
        
  # - name: posts-th
  #   label: Posts (TH)
  #   path: content/th/posts
  #   type: collection

    view:
      fields: [ title, date ]
      primary: title
      sort: [ date, title ]
      default:
        sort: title
        order: desc
      layout: tree
      node:
        filename: index.md
        hideDirs: all # This will hide all subfolders, even if they do not contain a node
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date }


